server {
    listen 80;
    server_name denuncia-ambiental.devverse.win;

    # 1. React Frontend
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # 2. Go API (Note the trailing slash behavior)
    location /api/ {
        proxy_pass http://api:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 3. Map Tiles
    location /tiles/ {
        proxy_pass http://map-server:8080/;
        proxy_set_header Host $host;
    }
}
